import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ManualService {


  public manualcom : Array<{en:Array<{
    titulo:String,
    titulointro:String,
    intro:String,
    tituloobjetivo:String,
    objetivo:String,
    tituloprocesotdi:String,
    proceso: String,
    imagenes1: String,
    titulotendencia:String,
    tendencia: String,
    imagenes2: String,
    tituloalcista:String,
    alcista: String,
    imagenes3: String,
    titulobajista:String,
    bajista: String,
    imagenes4: String,
    titulolateral:String,
    lateral: String,
    imagenes5: String,
    lateralb:String,
    imagenes6: String,
    lateralc: String,
    titulolocaliza:String,
    lacaliza: String,
    imagenes7: String,
    lacalizab: String,
    titulolocalizac:String,
    lacalizac: String,
    imagenes8: String,
    lacalizad: String,
    imagenes9: String,
    lacalizae: String,
    imagenes10: String,
    lacalizaf: String,
    imagenes11: String,
    vacio: String,
    titulocontexto:String,
    contexto: String,
    contextoa: String,
    titulocontextob:String,
    contextob: String,
    contextoc: String,
    nota: String,
    tituloglosario:String,
    glosario: String,
    tituloconclusion:String,
    conclusion: String,
    titulofinal:String,
    final: String,
    autor1: String,
    autor2: String,
    autor2A: String,
    autor3: String,
    autor4: String,
    linkapp:string
    }>
  es:Array<{
    titulo:String,
    titulointro:String,
    intro:String,
    tituloobjetivo:String,
    objetivo:String,
    tituloprocesotdi:String,
    proceso: String,
    imagenes1: String,
    titulotendencia:String,
    tendencia: String,
    imagenes2: String,
    tituloalcista:String,
    alcista: String,
    imagenes3: String,
    titulobajista:String,
    bajista: String,
    imagenes4: String,
    titulolateral:String,
    lateral: String,
    imagenes5: String,
    lateralb:String,
    imagenes6: String,
    lateralc: String,
    titulolocaliza:String,
    lacaliza: String,
    imagenes7: String,
    lacalizab: String,
    titulolocalizac:String,
    lacalizac: String,
    imagenes8: String,
    lacalizad: String,
    imagenes9: String,
    lacalizae: String,
    imagenes10: String,
    lacalizaf: String,
    imagenes11: String,
    vacio: String,
    titulocontexto:String,
    contexto: String,
    contextoa: String,
    titulocontextob:String,
    contextob: String,
    contextoc: String,
    nota: String,
    tituloglosario:String,
    glosario: String,
    tituloconclusion:String,
    conclusion: String,
    titulofinal:String,
    final: String,
    autor1: String,
    autor2: String,
    autor2A: String,
    autor3: String,
    autor4: String,
    linkapp:string
    }>
  por:Array<{
    titulo:String,
    titulointro:String,
    intro:String,
    tituloobjetivo:String,
    objetivo:String,
    tituloprocesotdi:String,
    proceso: String,
    imagenes1: String,
    titulotendencia:String,
    tendencia: String,
    imagenes2: String,
    tituloalcista:String,
    alcista: String,
    imagenes3: String,
    titulobajista:String,
    bajista: String,
    imagenes4: String,
    titulolateral:String,
    lateral: String,
    imagenes5: String,
    lateralb:String,
    imagenes6: String,
    lateralc: String,
    titulolocaliza:String,
    lacaliza: String,
    imagenes7: String,
    lacalizab: String,
    titulolocalizac:String,
    lacalizac: String,
    imagenes8: String,
    lacalizad: String,
    imagenes9: String,
    lacalizae: String,
    imagenes10: String,
    lacalizaf: String,
    imagenes11: String,
    vacio: String,
    titulocontexto:String,
    contexto: String,
    contextoa: String,
    titulocontextob:String,
    contextob: String,
    contextoc: String,
    nota: String,
    tituloglosario:String,
    glosario: String,
    tituloconclusion:String,
    conclusion: String,
    titulofinal:String,
    final: String,
    autor1: String,
    autor2: String,
    autor2A: String,
    autor3: String,
    autor4: String,
    linkapp:string
    }>}>;

constructor() {

this.manualcom=[{

en:[{
titulo:"MANUAL DE INSTRUCCIONES APPTDI© TRADING DECISIONS INVESTMENT APPTDI.COM",
titulointro:"INTRODUCCION",
intro:"El presente manual pretende servir de ayuda a las personas para educarse en inversión y que estén interesadas en incursionar en los mercados de valores. Y les sirva como una herramienta de apoyo para que sea un proceso lo más simple posible. Se pretende que cualquier persona pueda invertir en los mercados de capitales sin ser un experto, para ello la AppTDI© previo a un proceso de observación del mercado y el activo financiero determinado, se pueda valer de la AppTDI© para ayudar en el proceso más complejo del ser humano, como lo es tomar decisiones, más cuando son de inversión. Esta aplicación le provee de elementos de juicio en el análisis del activo financiero a invertir, y de este modo el margen de error se pueda reducir, dado que cuenta con información de análisis objetiva para que tome la mejor decisión, y elimine de cierto modocualquier elemento subjetivo. Con el propósito de ayudar a acercar el mercado a las personas y contribuir con la generación de fuentes de ingresos para las personas. Esta aplicación pretende ayudar a evitar pérdidas del capital y a evitar entrar tarde o en un momento inadecuado al mercado, y a obtener ganancias en tu portafolio. Por lo cual se pretende que sea una manera de generar una fuente real de ingresos adicionales para una persona que no es un experto pero que estaría interesado en incursionar como inversionista en los mercados de valores",
tituloobjetivo:"OBJETIVO DEL MANUAL",
objetivo:"El objetivo de este manual es el de Proveer al Trader/Inversionista principiante, o interesado en gestionar personalmente su portafolio de inversión, una herramienta para formarse y educarse en inversiones y apoyar el proceso de toma de decisión, sin tener que ser un experto. Para locual, ofrece las instrucciones e indicaciones necesarias para que el usuario comprenda y entienda el significado de cada una de las variables que debe ingresar en la AppTDI©, y que arroje los resultados o decisión sugeridos lo más aproximado posible. Y que dicha información sea ingresada de la forma correcta. De acuerdo a las condiciones de comportamiento del mercado del activo financiero analizado a gestionar. Aclarando que estas  ̈sugerencias ̈ no son determinantes, dado la dinámica constante del mercado, y que nunca se puede saber que va a suceder luego de ejecutar una acción u operación de compra y/o venta según sea el caso.",
tituloprocesotdi:"Proceso de la AppTDI",
proceso: "Para usar la aplicación correctamente y que nos arroje las alternativas de decisión que mejor se presentan, previamente tenemos que tener claro cuál es el activo que vamos a negociar, o que estamos negociando, y de esta forma ingresar los datos que identifican dicho activo (p.e Nasdaq,SP500, EURUSD, etc). Además es muy importante definir cuál es el marco de tiempo que vamos a analizar para configurar de una forma correcta la Aplicación AppTDI©. Si este es; Mensual, Semanal, Diario, 4 horas, 1 hora, 15m o 5m, como los más usados. Teniendo en cuenta que al ingresar el dato de la tercera variable CONTEXTO, se refiere al comportamiento del precio con relación al marco de tiempo inmediatamente anterior, p.e. si nuestro marco de tiempo principal es de 1hora el marco de tiempo del contexto debería de ser de 15m. Con el fin de evitar errores por parte del usuario/estudiante y/o trader/inversionista cuando va a ejecutar la AppTDI, esta ya viene configurada en algunas de las opciones, la más lógica de acuerdo a la variable anterior previamente determinada en la variable LOCALIZACION. Por lo tanto, esto nos va a permitir ubicarnos en el tiempo e ingresar la información correcta para que la AppTDI©, nos arroje la mejor alternativa de decisión que debemos tomar en ese momento.Además, es muy importante estar actualizando la información del comportamiento del precio que vamos observando, según el marco de tiempo definido para el análisis, dado que como sabemos el mercado es dinámico y en constante movimiento. Por lo cual, debemos actualizar permanentemente la información de la AppTDI©, de acuerdo a la variable Marco de Tiempo, de nuestro análisis. El instrumento que sugerimos se debe utilizar es uno de los más populares y usados por los expertos e inversionistas del mercado en la industria. La Vela Japonesa, dado que es el indicador que mejor refleja el comportamiento del precio de un activo financiero en un periodo de tiempo determinado, porque muestra el precio de apertura y de cierre, el máximo y mínimo nivel al que llego a ser negociado durante un periodo de tiempo, que es cuando finalmente se forma la vela.",
imagenes1: "./assets/imagenes/IMAGEN EXPLICACION VELA JAPONESA.PNG",
titulotendencia:"VARIABLE: TENDENCIA.",
tendencia: "La primera variable o paso que debemos ingresar en la aplicación, una vez previamente hayamos decidido el activo a analizar y/o negociar, y el marco de tiempo en el cual pretendemos operarlo. Es la Tendencia. La cual puede ser Alcista, Bajista o Lateral. Cualquier activo solo puede hacer este movimiento. Por lo cual, para el ingreso de la información en esta primer variable debe ir de acuerdo con el marco de tiempo principal, ósea (Marco de tiempo seleccionado para analizar y/o negociar un activo deseado, p.e; Daily, 4Hr, 1Hr, 15m 5m) sobre el cual vamos a tomar ciertadecisión de inversión, y estaremos dispuestos a esperar como mínimo ese mismo tiempo para obtener un resultado. Nuestra capacidad de identificar la tendencia y operar en la dirección de la tendencia ofrecerá la mayor probabilidad en nuestras operaciones, y nos va a permitir ingresar el dato correcto que requiere la variable número uno para configurar la mejor alternativa. Nos concentraremos en las3 tendencias primarias: la Tendencia Alcista, Tendencia Lateral y Tendencia Bajista. Para tendencias alcistas y bajistas negociaremos en la dirección de la tendencia. Para la tendencia lateral usted no deberá sino identificarla e ingresar dicha apreciación, y la aplicación AppTDI© se encargará de mostrarle si debe operar en algún sentido o esperar a que se defina dicha tendencia sea al alza o la baja. Buscaremos patrones, formaciones, eventos o movimientos de corrección en contra de la tendencia para entradas a favor de la tendencia. Las tendencias frecuentemente terminan cuando se ha rellenado un vacío de precios, cuando se tornan extendidas o cuando alcanzan el Mínimo/Máximo en un marco de tiempo mayor. Estamos atentos a estos movimientos claves de reversión para evitar entrar en la tendencia demasiado tarde, y posiblemente para entrar temprano en la nueva tendencia. Igualmente nuestra aplicación AppTDI©, le mostrara una vez ingrese las variables, cual es la mejor alternativa de decisión y el grado de prioridad. ¡Solo debe actuar con determinación...! Usaremos los Rebotes y/o Retrocesos o formaciones de velas como se muestra en la gráfica para determinar la tendencia. H = High ó Máximo L = Low ó Mínimo",
imagenes2: "./assets/imagenes/IMAGEN EXPLICACION  RETROCESOS Y REBOTES.PNG",
tituloalcista:"Tendencia Alcista:",
alcista: "Se establece con 2 Retrocesos en Punta Superiores (RPM), y 2 Rebotes en Punta Inferiores (RIP). También conocidos en el análisis técnico como Pivots Points (puntos pivotes).",
imagenes3: "./assets/imagenes/IMAGEN EXPLICACION TENDENCIA ALCISTA.PNG",
titulobajista:"Tendencia Bajista:",
bajista: "Se establece con 2 Retrocesos en Punta Superiores (RPS) y 2 Rebotes en Punta Inferiores (RPI). También conocidos en el análisis técnico como Pivots Points (puntos pivotes).",
imagenes4: "./assets/imagenes/EXPLICACION TENDENCIA BAJISTA.PNG",
titulolateral:"Tendencia Lateral:",
lateral: "Las Tendencias Laterales pueden continuar con la tendencia previa o iniciar una nueva tendencia en la dirección opuesta. Negociar dentro de una tendencia lateral puede presentar oportunidades en ambas direcciones. Puede generarse de dos formas, si viene de una tendencia alcista o bajista respectivamente. Cuando la precede una tendencia Alcista: Una tendencia lateral puede ser una corrección en medio de una tendencia alcista, se puede definir con 2 Retrocesos en Punta o más en Zonas de Precios Superiores (ZPS) relativamente iguales, y 2 Rebotes en Punta o más en Zonas de Precios Inferiores (ZPI) relativamente iguales, y el sesgo a favor de la tendencia previa (alcista).",
imagenes5: "./assets/imagenes/EXPLICACION TENDENCIA LATERAL PAUSA ALCISTA.PNG",
lateralb:"Cuando la precede una Tendencia Bajista: Una Tendencia Lateral puede ser una corrección dentro de una tendencia bajista y se puede definir con 2 o más Rebotes en Punta en Zonas de Precios Inferiores (ZPI) relativamente iguales, y 2 o más Retrocesos en Punta en Zonas de Precios Superiores (ZPS) relativamente iguales y el sesgo es a favor de la tendencia previa (bajista).",
imagenes6: "./assets/imagenes/EXPLICACION TENDENCIA LATERAL PAUSA BAJISTA.PNG",
lateralc: "Abreviatura Requerida para el Ingreso de la Variable Tendencia en Pagina AppTDI©, donde se deberá escoger alguna de estas variables según sea el caso. Alcista , Bajista , Lateral ",
titulolocaliza:"VARIABLE: LOCALIZACIÓN:",
lacaliza: "Esta variable se refiere a la ubicación o localización que está teniendo el precio del activo financiero en el marco de tiempo principal o escogido para negociar, y el cual pretendemos analizar para negociarlo y tomar una decisión de invertir. Como en la variable Tendencia, es muy importante definir correctamente la opción de esta variable, y definir en donde se encuentra ubicado el precio para obtener la mejor opción. Y para ello vamos a dar una explicación sobre el significado de cada una de las opciones que tenemos para esta variable. En los mercados financieros existen una variedad de instrumentos y herramientas (indicadores y osciladores), para ser usados en el análisis técnico de los mercados de valores, tales como; barras de precio, líneas, Macd, RSI, Ichimoku, Niveles Fibonacci, Promedios Móviles, Exponenciales o líneas de tendencia, etc. Y ser considerados para hacer el conocido análisis técnico. Como lo hemos dicho nos vamos a concentrar en la acción del precio; representado por la vela japonesa. Y su Localización en zonas de precios conocidas también como zonas de soporte y/o resistencia, que pueden servir para determinar la ubicación del precio dentro de la tendencia. Debemos recordar que el único soporte y resistencia Verdadero y Real es el  ̈Precio ̈, y esta es la clave del Análisis Técnico Objetivo. El Verdadero y Real Soporte y Resistencia son los Máximos y Mínimos de Precios de velas previos, una serie de Velas de Precios que forman una base, o un vacío de precios sin rellenar entre velas de precio. En la gráfica se puede observar la ubicación o Localización del precio en niveles en donde normalmente los precios probablemente rebotan o retroceden formando de este modo y confirmando las tendencias. Es aquí donde debemos observar y analizar muy bien cuál es la ubicación del precio para ingresar correctamente la opción LOCALIZACION requerida en la página de la AppTDI.",
imagenes7: "./assets/imagenes/IMAGEN EXPLICACION VARIABLES LOCALIZACION.PNG",
lacalizab: "Para el ingreso de esta variable a nuestra AppTDI©, vamos a definir cada una de las opciones que estarán disponibles en una lista de selección, y sea de fácil manejo para el usuario de la aplicación. Técnicamente el precio de un activo financiero siempre estará ubicado en una zona de precios, que va en relación con la tendencia previa, o simplemente se encontrara en un VACIO de precios. Pero básicamente el precio se encontrará ubicado en estas zonas. Es de vital importancia analizar el comportamiento del precio en el activo a negociar para ingresar la información correcta y que nuestra aplicación pueda mostrar la mejor opción para ese momento del mercado.",
titulolocalizac:"Opciones de Elección Variable Localización:",
lacalizac: "Retrocesos en Zonas de Precios Potentes Superiores: o también llamadas Resistencia Mayor, esta opción la debes escoger solo cuando el precio se encuentre en tendencia lateral y el precio ha hecho Retrocesos en una Zona de Precios Potente en la parte superior al menos dos veces como se muestra en la gráfica. Una Tendencia Lateral puede ser una corrección dentro de una tendencia bajista. El sesgo a favor de la tendencia previa (bajista).",
imagenes8: "./assets/imagenes/IMAGEN RETROCESO ZONA PRECIOS POTENTES SUPERIORES.PNG",
lacalizad: "Retroceso a Zona Precios Superior: o también conocida como Resistencia Menor, esta opción la debes escoger cuando el precio se encuentre en tendencia bajista, y el precio ha roto una Zona de Precios, mínimos previos, o línea de soporte previo, y Retrocede hasta el nivel de precios que ha roto. Técnicamente este movimiento se conoce como ruptura de soporte que ahora se convierte en resistencia. Es en esa zona de precios donde debes buscar la mejor entrada para posicionarse en cortos o ventas, teniendo en cuanta que la vela del marco de tiempo escogido este formada.",
imagenes9: "./assets/imagenes/IMAGEN RETROCESO A ZONA PRECIOS SUPERIOR.PNG",
lacalizae: "Rebotes en Zonas de Precios Potentes Inferiores: o también conocida como Soporte Mayor, esta opción la debes escoger solo cuando el precio se encuentre en tendencia lateral y el precio ha hecho Rebotes en una Zona de Precios Potente en la parte inferior al menos dos veces como se muestra en la gráfica. Una Tendencia Lateral puede ser una corrección dentro de una tendencia alcista. El sesgo a favor de la tendencia previa (alcista)",
imagenes10: "./assets/imagenes/IMAGEN RETROCESO ZONA PRECIOS POTENTES SUPERIORES.PNG",
lacalizaf: "Rebote a Zona de Precios Inferior: o también conocida como Soporte Menor, esta opción la debes escoger cuando el precio se encuentre en tendencia alcista, y el precio ha roto una línea de resistencia previa, máximos previos, y rebota en los niveles de precio que ha roto. Técnicamente este movimiento se conoce como ruptura de una resistencia que ahora se convierte en soporte. Es en esa zona de precios donde debes buscar la mejor entrada para posicionarte en largos o compras, teniendo en cuenta que la vela del marco de tiempo escogido este formada.",
imagenes11: "./assets/imagenes/REBOTE A ZONA PRECIOS INFERIOR.PNG",
vacio: "Vacío: Esta opción la debes escoger cuando básicamente el precio no tenga niveles o zonas de precios cercanos, mínimos o máximos de velas previas, o una serie de velas, que puedan indicar un nivel de Resistencia o Soporte. Pero se toman como los siguientes niveles de Soporte o Resistencia los mismos factores. En la tendencia lateral se favorecen los posibles rebotes o retrocesos fallidos.",
titulocontexto:"VARIABLE: CONTEXTO:",
contexto: "En esta variable, debemos ingresar en nuestra AppTDI© el Contexto, y hace referencia al comportamiento del precio analizando los marcos de tiempo. Por lo cual, como lo hemos mencionado, es necesario definir previamente, en la opción MARCO DE TIEMPO. Cual será ese marco de tiempo para observar el comportamiento del activo financiero que hemos decidido negociar o analizar en determinado momento. Cuando todos los marcos de tiempo se encuentran alineados las probabilidades aumentan. Cada marco de tiempo puede tener una tendencia distinta, y esperar que todos los marcos de tiempo estén alineados puede producir indecisión.",
contextoa: "Por lo tanto, en la utilización de la AppTDI©, usted debe observar cual es el comportamiento que está teniendo el precio del activo del marco de tiempo inferior con respecto a su marco de tiempo principal, ósea, marco de tiempo escogido para negociar. O Analizar frente a sus marcos de tiempo inferiores, para poder percibir su contexto e ingresar la opción correcta. A continuación sugerimos los marcos de tiempo más adecuados para analizar e ingresar en la aplicación. El marco de tiempo Mensual con el marco de tiempo semanal para una Estrategia Core. El marco de tiempo Semanal con el marco de tiempo Diario para una Estrategia Swing. El marco de tiempo Diario con el marco de tiempo de 4 horas para una Estrategia Swing – Intradía. El marco de tiempo de 4 horas con el marco de tiempo de 1 hora para una Estrategia Intradía. El marco de tiempo de 1 hora con el marco de tiempo de 15 minutos para una Estrategia Intradia – Scalp. El marco de tiempo de 15 minutos con el marco de tiempo de 5 minutos para una Estrategia Scalping. Es su decisión escoger cual es la estrategia sobre el MARCO de TIEMPO de su elección, y que se acomode según sus expectativas o metas de inversión que más se acomodan a su estilo de trading, grado de aversión al riesgo, y su naturaleza. Le recomendamos que tenga esto muy en cuenta y revise nuestro Disclaimer. Es muy importante actualizar la información de la AppTDI©, cada vez que se cumpla el marco de tiempo principal y se forme la vela del MARCO DE TIEMPO PRINCIPAL escogido y seleccionado para el análisis o gestión de su inversión. Recuerde, una vela no se forma hasta que se forma, no se anticipe, nunca se sabe lo que puede suceder en los mercados!.",
titulocontextob:"Opciones Variable Contexto:",
contextob: "Impulsivo de Tendencia: Esta opción hace referencia al movimiento que está teniendo el precio desde el marco de tiempo inferior sobre el principal, el cual fue el escogido para ser analizado y/o negociado. (p.e. Si decidió elegir el Marco de Tiempo 4horas, debe observar cómo se están comportando los marcos de tiempo inferiores frente al de 4horas, y como se menciona tiende a impulsar la tendencia).",
contextoc: "Correctivo de Tendencia: Esta opción hace referencia al movimiento que está teniendo el precio del activo financiero seleccionado, desde su marco de tiempo inferior sobre el marco de tiempo del principal o seleccionado para ser analizado y/o negociado. Y hace referencia a que está tendiendo a corregirse con relación a la tendencia que se ha seleccionado en la Variable Tendencia. (p.e. Si se escoge en la variable tendencia; Bajista. El comportamiento esperado es que el precio se corrija). Extremo del Rango: Esta opción hace referencia a la ubicación del precio del activo financiero seleccionado para observación o negociación desde el marco de tiempo inferior sobre el marco de tiempo del principal seleccionado para ser analizado y/o negociado.",
nota: "*Nota: con el propósito de minimizar el margen de error por parte del estudiante o aprendiz, cuando se ha hecho una correcta elección de las dos primeras variables, las posibles elecciones para esta variable se pueden ver reducidas, incluso a solo una. Ósea que solo debe escogerla. Dado que en ciertos momentos del mercado el precio en estas zonas de precios no tiene muchas opciones para moverse debido a las zonas donde se encuentra.",
tituloglosario:"GLOSARIO Y TERMINOLOGIA:",
glosario: "Mercados de valores: Es el lugar en donde confluyen las fuerzas de la oferta y la demanda de activos financieros y de capital. Pueden ser físicos, electrónicos etc./NYSE, CME, CBO, NASDAQ, BOVESPA, NYKKEI, FTSE, etc.) Activo financiero: es un instrumento que contiene un valor económico y el cual representa la tenencia o representación de propiedad sobre una parte de un bien, puede ser de una acción de  una empresa u otro título valor, por ejemplo, Acciones de Apple, Amazon, Google, etc. O de índices como el Dow Jones, S&P500 o Nasdaq, en Forex EURUSD, GBPUSD, USDCHF, etc. O de cualquier otro instrumento financiero existente. Vela Japonesa: Es un indicador financiero que es utilizado desde hace siglos para definir el precio de activo o bien, teniendo un precio de Apertura, Cierre, un Maximo al que fue negociado, y un Mínimo al que fue negociado, en un determinado periodo de tiempo. Marco de Tiempo: Se refiere al tiempo definido de análisis para un activo financiero determinado. Por ejemplo, Mensual, Semanal, Diario, 4 horas, 1 hora, 15 minutos y 5 minutos. Opciones Binarias: instrumento financiero de inversión el cual consiste en invertir sobre un activo financiero que te ofrece dos opciones de inversión (Call – Put), y la opción de hacerla efectiva en un periodo de tiempo determinado. Firma Broker: Entidad financiera regulada para ofrecer servicios de intermediación financiera, y que ofrece los servicios de acceso al mercado a través de una cuenta o portafolio de inversión. Entre muchas otras más, estas son solo algunas de las que vas a ver en el manual y la aplicación. Si deseas alguna explicación especial sobre un término o vocabulario que no entiendas, me escribes y con gusto te lo puedo explicar y enriquecer este manual.",
tituloconclusion:"Conclusión:",
conclusion: "El sentido con el que se pensó crear esta aplicación fue el de acercar el mercado a las personas y ser una herramienta de apoyo en la gestión de un portafolio de inversión, y que el usuario y/o inversionista tenga elementos de juicio para tratar de minimizar el margen de error y evitar en lo posible las pérdidas del capital. Esto es lo que me motivo a crear esta Aplicación, y mi mayor deseo es contribuir a que puedas tener una fuente adicional de ingresos.",
titulofinal:"Recomendación Final:",
final: "Como lo he mencionado arriba, no pretendo con esta Aplicación prometerte nada, solo quiero ayudar y compartir lo mucho o poco que he aprendido y vivido en el mundo del Trading Bursátil, y convertir mi conocimiento y experiencia en un instrumento que te pueda ayudar, y lo quiero compartir contigo. Esta aplicación es solo el inicio, el primer paso, para que inicies un camino apasionante en el trading, pero que debes estar dispuesto a dar y prepararte para ser cada vez mejor y puedas generar fuentes de ingreso. Eso es lo que más deseo para tu vida.",
autor1: "Gracias por la oportunidad.",
autor2: "Con Afecto",
autor2A: "John Alexander Vieira Marín",
autor3: "Creador de AppTDI  :",
autor4: "www.apptdi.com",
linkapp: "https://apptdi.com/disclaimer/"
}],
es:[{
titulo:"APPTDI© INSTRUCTION MANUAL TRADING DECISIONS INVESTMENT APPTDI.COM",
titulointro:"INTRODUCTION",
intro:"This manual is intended to help people educate themselves on investment so that they will have a better experience and be able to correctly use and take better advantage of the AppTDI©. With the purpose of entering the stock markets. And serve them as a support tool to make the process as simple as possible. It is intended that any person can invest in the capital markets without being an expert, so that the AppTDI© prior to a process of observation of the market and the given financial asset, can use the AppTDI© to help in the most complex process of the human being, such as making decisions, more when it comes to investment. This application provides you with elements of judgment in the analysis of the financial asset to be invested, and in this way the margin of error can be 'reduced', given that it has objective analysis information so that you can make the best decision, and eliminate in some way any subjective element. Which is the most normal mistake that traders or investors make due to lack of discipline to follow a method or process. In order to help bring the market closer and contribute to the generation of income sources for people. This application aims to help in the analytical process of observation and discipline in the monitoring of a financial asset in which you want to invest, in order to avoid losses of capital, avoid entering the market late or at an inappropriate time, and to obtain profits in your portfolio. Therefore, the ultimate goal is that it contributes in some way to generate a real source of additional income for a person who is not an expert but would be interested in entering as an investor in the stock markets, decreasing or shortening the time in its learning curve.",
tituloobjetivo:"OBJECTIVE OF THE MANUAL",
objetivo:"El objetivo de este manual es el de Proveer al Trader/Inversionista principiante, o interesado en gestionar personalmente su portafolio de inversión, una herramienta para formarse y educarse en inversiones y apoyar el proceso de toma de decisión, sin tener que ser un experto. Para locual, ofrece las instrucciones e indicaciones necesarias para que el usuario comprenda y entienda el significado de cada una de las variables que debe ingresar en la AppTDI©, y que arroje los resultados o decisión sugeridos lo más aproximado posible. Y que dicha información sea ingresada de la forma correcta. De acuerdo a las condiciones de comportamiento del mercado del activo financiero analizado a gestionar. Aclarando que estas  ̈sugerencias ̈ no son determinantes, dado la dinámica constante del mercado, y que nunca se puede saber que va a suceder luego de ejecutar una acción u operación de compra y/o venta según sea el caso. The objective of this manual is to provide the novice trader/investor, or those interested in personally managing their investment portfolio, with a tool to train themselves, educate themselves in investments and support the decision-making process, without having to be an expert. To this end, it offers the necessary instructions and indications so that the user understands and comprehends the meaning of each of the variables that must be entered into the AppTDI©, and that it gives the suggested results or decision as close as possible. And that this information is entered correctly. According to the market behavior conditions of the financial asset analyzed and to be managed. Clarifying that these  ̈Results / Decisions ̈ are not determining, given the constant dynamics of the market, and that you can never know what will happen after executing an action or purchase and/or sale operation as the case may be. Given the number of conditions and circumstances that could arise once the order is executed by the investor based on the result of the AppTDI©.",
tituloprocesotdi:"AppTDI Process",
proceso: "To use the application correctly and that it shows us the alternatives of decision that better are presented. Previously we must have clear which is the asset that we are going to negotiate, and this way to enter the data that identify this asset (e.g. Nasdaq, SP500, EURUSD, etc). In the option assigned for this variable. In addition, it is very important to define what is the time frame that we are going to analyze to configure the AppTDI© application correctly. If this is; Monthly, Weekly, Daily, 4 hours, 1 hour, 15m or 5m, as the most used. Taking into account that, when entering the data of the third variable, CONTEXT, it refers to the behavior of the price in relation to the immediately previous time frame, i.e. if our main time frame is 1 hour, the context time frame should be 15m below and 4 hours above to have a better view of that context. In order to avoid errors by the user/student and/or trader/investor when you are going to run the AppTDI, it is already configured in some of the options, the most logical according to the previous variable previously determined in the LOCATION variable. Therefore, this will allow us to locate ourselves in time and enter the correct information so that the AppTDI©, gives us the best alternative of decision that we must take at that moment. In addition, it is very important to be updating the information of the price behavior that we are observing, according to the time frame defined for the analysis, since as we know the market is dynamic and in constant movement. Therefore, we must permanently update the information of the AppTDI©, according to the variable Time Frame, of our analysis. And to fulfill the purpose of the tool, which is to have discipline in monitoring the market. The instrument we suggest to use is one of the most popular and used by market experts and investors in the industry. The Japanese Candle, because it is the indicator that best reflects the price behavior of a financial asset in a given period of time, and because it shows the opening and closing price, the maximum and minimum, level at which it came to be traded during a period of time, which is when the candle is finally formed.",
imagenes1: "q",
titulotendencia:"VARIABLE: TREND..",
tendencia: "The first variable or step that we must enter in the application, once we have previously decided the asset to be analyzed and/or negotiated, and the time frame in which we intend to operate it. It is the Trend. Which can be Bullish, Bearish or Lateral. Any asset can only make this move. Therefore, to enter the information in this first variable it must be in accordance with the main time frame, i.e. (Time frame selected to analyze and/or trade a desired asset, i.e. Daily, 4Hr, 1Hr, 15m 5m) on which we are going to make a certain investment decision, and we will be willing to wait at least that same time to obtain a result. Our ability to identify the trend and operate in the direction of the trend will offer the highest probability in our operations, and will allow us to enter the correct data required by the number one variable to configure the best alternative. We will concentrate on the 3 primary trends: the Uptrend, the Side Trend and the Downtrend. For both up and down trends we will trade in the direction of the trend. For the lateral trend you will only have to identify it and enter that appreciation, and the AppTDI© application will show you if you should trade in any sense or wait for that trend to be defined as up or down. We will look for patterns, formations, events or counter-trend movements for pro-trend entries. Trends often end when a price gap has been filled, when they become extended, or when they reach the Minimum/Maximum in a longer time frame. We watch for these key reversal movements to avoid entering the trend too late, and possibly to enter the new trend early. Likewise our AppTDI© application, will show you once you enter the variables, which is the best decisio  alternative and the degree of priority, you just have to act with determination...! We will use the Rebound and/or Rewind or candlestick formations as shown in the graph to determine the trend. H = High ó Maximum L = Low ó Minimum",
imagenes2: "q",
tituloalcista:"Peak setbacks:",
alcista: "It is established with 2 Upper Point Regressions (RPM), and 2 Lower Point Rebounds (RIP). Technically known as Pivots.",
imagenes3: "q",
titulobajista:"Downward Trend:",
bajista: "It is established with 2 upper end rebounds (RPS) and 2 lower end rebounds (RPI). Or Pivot Points.",
imagenes4: "q",
titulolateral:"Lateral Trend:",
lateral: "Side Trends can either continue the previous trend or initiate a new trend in the opposite direction. Trading within a lateral trend can present opportunities in both directions. It can be generated in two ways, if it comes from an uptrend or downtrend respectively. When preceded by an uptrend: A lateral trend can be a correction in the middle of an uptrend, it can be defined with 2 Peak Rebounds or more in relatively equal Upper Price Zones (PSZ), and 2 Peak Rebounds or more in relatively equal Lower Price Zones (LTZ), and the bias in favor of the previous (uptrend) trend.",
imagenes5: "q",
lateralb:"When preceded by a Downward Trend: A Sideways Trend can be a correction within a downward trend and can be defined as 2 or more Peak Rebounds in relatively equal Lower Price Zones (LTZs), and 2 or more Peak Rebounds in relatively equal Upper Price Zones (UZs) and the bias is in favor of the previous (downward) trend",
imagenes6: "q",
lateralc: "Abbreviation Required for Trend Variable Entry in AppTDI Page.• Upward • Downward Trend • Lateral",
titulolocaliza:"VARIABLE: LOCATION:",
lacaliza: "This variable refers to the placement or location that the price of the financial asset is having in the main or chosen time frame for trading, and which we intend to analyze in order to negotiate and make an investment decision. As in the Trend variable, it is very important to correctly define the option of this variable, and define where the price is located to obtain the best option. And for this we will give an explanation of the meaning of each of the options we have for this variable. In the financial markets there are a variety of instruments and tools (indicators and oscillators), to be used in the technical analysis of the stock markets, such as; price bars, lines, Macd, RSI, Ichimoku, Fibonacci levels, Moving Averages, Exponentials or trend lines, etc. And be considered to do the well known technical analysis. As we have said we are going to concentrate on price action; represented by the Japanese candlestick. And its location in price zones also known as support and/or resistance zones, which can serve to determine the location of the price within the trend. We must remember that the only True and Real support and resistance is  ̈Price ̈, and this is the key to Objective Technical Analysis. The True and Real Support and Strength is the Price Maximums and Minimums of previous candles, a series of Price Candles that form a base, or an unfilled price gap between Price Candles. In the graph you can see the placement or location of the price in levels where normally prices are likely to bounce back or rebound, thus forming and confirming trends. It is here where we must observe and analyze very well what is the location of the price to correctly enter the option LOCATION required in the AppTDI page.",
imagenes7: "q",
lacalizab: "To enter this variable in our AppTDI©, we will define each of the options that will be available in a selection list and be easy to use for the user of the application. Technically, the price of a financial asset will always be located in a price zone, which goes in relation to the previous trend, or it will simply be in a price VACUUM. But basically the price will be located in these zones. It is of vital importance to analyze the behavior of the price of the asset to be negotiated in order to enter the correct information so that our application can show the best option for that moment in the market.",
titulolocalizac:"VARIABLE CHOICE OPTIONS LOCATION:",
lacalizac: "Rollbacks in Higher Power Price Zones: or also called Higher Resistance, this option should be chosen only when the price is in a lateral trend and the price has rolled back in a Higher Power Price Zone at the top at least twice as shown in the chart. A Sideways Trend can be a correction within a downward trend. The bias in favor of the previous (downward) trend.",
imagenes8: "q",
lacalizad: "Return to Higher Price Zone: or also known as Lower Resistance, this option should be chosen when the price is in a downward trend, and the price has broken a previous Price Zone, low, or support line, and returns to the price level it has broken. Technically this move is known as a breakout of support which now becomes resistance. It is in that price zone where you should look for the best entry to position in short or sell, keeping in mind that the candle in the chosen time frame is formed.",
imagenes9: "q",
lacalizae: "Bounces in Lower Powerful Price Zones: or also known as Major Support, this option should be chosen only when the price is in a lateral trend and the price has bounced in a Powerful Price Zone at the bottom at least twice as shown in the chart. A Sideways Trend can be a correction within an upward trend. The bias in favor of the previous (upward) trend.",
imagenes10: "q",
lacalizaf: "Bounce to Lower Price Zone: or also known as Minor Support, this option should be chosen when the price is in an uptrend, and the price has broken a previous resistance line, previous highs, and bounces off the price levels it has broken. Technically this move is known as a breakout of a resistance that now becomes support. It is in that price zone where you should look for the best entry to position yourself in long or buys, keeping in mind that the candlestick in the chosen time frame is formed.",
imagenes11: "q",
vacio: "Empty: This option should be chosen when the price basically has no close price levels or areas, minimum or maximum of previous candles, or a series of candles, which may indicate a level of Resistance or Support. But the following levels of Support or Resistance are taken as the same factors. The lateral trend favors possible failed rebounds or reversals.",
titulocontexto:"VARIABLE: CONTEXT:",
contexto: "In this variable, we must enter in our AppTDI© the Context, and it refers to the price behavior by analyzing the time frames. Therefore, as we have mentioned, it is necessary to define previously, in the option TIME FRAME. What will be that time frame to observe the behavior of the financial asset that we have decided to negotiate or analyze at a given time. When all the time frames are aligned the probabilities increase. Each time frame can have a different trend, and waiting for all time frames to be aligned can lead to indecision. Therefore, when using the AppTDI©, you should observe which is the behavior that the price of the asset in the lower time frame is having with respect to your main time frame, that is, the time",
contextoa: "rame chosen to negotiate. Or Analyze against your lower time frames, in order to perceive their context and enter the correct option Below we suggest the most appropriate time frames to analyze and enter the application. The Monthly time frame with the weekly time frame for a Core Strategy The Weekly time frame with the Daily time frame for a Swing Strategy. The Daily time frame with the 4 hour time frame for a Swing - Intraday Strategy. The 4 hour time frame with the 1 hour time frame for an Intraday Strategy The 1 hour time frame with the 15 minute time frame for an Intraday Strategy - Scalp.The 15 minute time frame with the 5 minute time frame for a Scalping Strategy. It is up to you to choose which strategy over the TIMEFRAME of your choice, and which fits your expectations or investment goals that best fit your trading style, degree of risk aversion, and nature. We recommend that you keep this in mind and review our Disclaimer. It is very important to update the AppTDI© information, every time the main time frame is met and the candle is formed of the MAIN TIME FRAME chosen and selected for the analysis or management of your investment. Remember, a candle is not formed until it is formed, do not anticipate, you never know what may happen in the markets!",
titulocontextob:"Options Variable Context:",
contextob: "Trend Impulse: This option refers to the movement the price is having from the lower time frame over the main one, which was chosen to be analyzed and/or negotiated (i.e. if you decided to choose the 4 hour time frame, you should observe how the lower time frames are behaving versu the 4 hour time frame, and as mentioned it tends to push the trend). Trend Correction: This option refers to the movement that the price of the selected financial asset is having, from its lower time frame over the time frame of the principal or selected to be analyzed and/or traded. And it refers to the fact that it is tending to correct itself in relation to the trend that has been selected in the Trend Variable (i.e. if chosen in the trend variable; Downward). The expected behavior is that the price is corrected).",
contextoc: "End of Range: This option refers to the location of the price of the financial asset selected for observation or negotiation from the lower time frame over the time frame of the principal selected for analysis and/or negotiation.",
nota: "*Note: In order to minimize the margin of error by the student or trainee, when a correct choice of the first two variables has been made, the possible choices for this variable can be reduced, even to just one. So you should only choose one. Given that at certain times of the market the price in these price zones does not have many options to move because of the zones where it is located.",
tituloglosario:"GLOSSARY AND TERMINOLOGY:",
glosario: "Stock markets: It is the place where the forces of supply and demand of financial and capital assets meet. They can be physical, electronic, etc. (NYSE, CME, CBO, NASDAQ, BOVESPA, NYKKEI, FTSE, etc.) Financial asset: it is an instrument that contains an economic value and which represents the possession or representation of property over a part of a good, it can be a share of a company or another security, for example, Apple shares, Amazon, Google, etc. Or from indices such as the Dow Jones, S&P500 or Nasdaq, in Forex EURUSD, GBPUSD, USDCHF, etc. Or any other existing financial instrument. Japanese Candle: It is a financial indicator that has been used for centuries to define the price of an asset or, having an Open, Close price, a Maximum at which it was traded, and a Minimum at which it was traded, in a certain period of time. Time frame: Refers to the defined time of analysis for a given financial asset. For example, Monthly, Weekly, Daily, 4 hours, 1 hour, 15 minutes and 5 minutes. Binary Options: financial investment instrument which consists of investing in a financial asset that offers two investment options (Call - Put), and the option to make it effective in a determined period of time. Broker Firm: Financial entity regulated to offer financial intermediation services, and that offers the services of access to the market through an account or investment portfolio. Among many others, these are only some of the ones you will see in the manual and the application. If you would like some special explanation of a term or vocabulary that you do not understand, write to me and I will gladly explain and enrich this manual.",
tituloconclusion:"Conclusion:",
conclusion: "The idea behind the creation of this application was to bring the market closer to the people and to be a support tool in the management of an investment portfolio, and that the user and/or investor have elements of judgment to try to minimize the margin of error and avoid capital losses as much as possible. This is what motivated me to create this application, and my greatest desire is to contribute to you having an additional source of income",
titulofinal:"Final Recommendation:",
final: "As I mentioned above, I do not intend with this Application to promise you anything, I just want to help and share how much or how little I have learned and lived in the world of Stock Trading, and turn my knowledge and experience into an instrument that can help you, and I want to share it with you. This application is only the beginning, the first step, so you can start an exciting path in trading, but you must be willing to give and prepare to be better and better and you can generate sources of income. That is what I want most for your life.",
autor1: "Thank you for the opportunity.  ",
autor2: "With Affection",
autor2A: "John Alexander Vieira Marín",
autor3: "AppTDI Creator :",
autor4: "www.apptdi.com",
linkapp:"https://apptdi.com/disclaimer/"
}],
por:[{
titulo:"MANUAL DE INSTRUÇÕES APPTDI© TRADING DECISIONS INVESTMENT APPTDI.COM",
titulointro:"INTRODUÇÃO",
intro:"Este manual tem o intuito de servir de ajuda às pessoas para se educarem sobre investimentos e para que tenham uma experiência melhor e possam usar corretamente e aproveitar da melhor maneira o AppTDI©. Com o propósito de entrar na bolsa de valores e que sirva como uma ferramenta de apoio para que seja um processo mais simples possível. Pretende-se que qualquer pessoa possa investir nos mercados de capitais sem ser um expert, para isso o AppTDI© realiza um processo de observação do mercado e do determinado ativo financeiro. Você pode usar o AppTDI© para te ajudar no processo mais complexo do ser humano, como o de tomar decisões, especialmente quando se trata sobre investimentos. Este aplicativo fornece elementos de julgamento na análise de qual ativo financeiro investir e, deste modo, é possível “reduzir” a margem de erro, já que conta com informações de análise objetiva para que tome a melhor decisão e elimine, de certo modo, qualquer elemento subjetivo. Que é o erro mais normal que os traders e os investidores cometem por falta de disciplina para seguirem um método ou processo. Com a finalidade de ajudar a familiarizar com o mercado e de contrubuir com a geração de fontes de renda para as pessoas. Este aplicativo pretende ajudar no processo analítico de observação e disciplina no monitoramento de um ativo financeiro, o qual se deseja investir, com o propósito de evitar perdas de capital, evitar entrar tarde ou em um momento inadequado ao mercado, e a obter ganhos em sua carteira. Portanto, o objetivo final é que contribua, de alguma maneira, a gerar uma fonte real de recursos adicionais para uma pessoa que não é expert, mas que esteja interessada em se aventurar como investidor na bolsa de valores, diminuindo o tempo em sua curva de aprendizagem.",
tituloobjetivo:"OBJETIVO DO MANUAL",
objetivo:"EO objetivo deste manual é fornecer ao Trader/Investidor, iniciante ou interessado em gerir pessoalmente sua carteira de investimentos, uma ferramenta para treinar, educar-se sobre investimentos e sustentar o processo de tomada de decisão sem precisar de ser um expert. Para isso, oferece as instruções e indicações necessárias para que o usuário compreenda e entenda o significado de cada uma das variáveis que devem ser inseridas no AppTDI© e que tenha os resultados ou decisões sugeridos os mais aproximados possíveis. E que tal informação seja inserida da forma correta. De acordo com as condições de comportamento do mercado do ativo financeiro analisado e a ser gerenciado. Esclarecendo que esses “Resultados/Decisões” não são decisivos, devido à constante dinâmica do mercado e que nunca pode-se saber o que irá acontecer após executar uma ação ou operação de compra e/ou venda, conforme o caso. Dado a quantidade de condições e circunstâncias que podem surgir uma vez que a ordem for executada pelo investidor, com base no resultado obtido pelo AppTDI©.",
tituloprocesotdi:"Processo do AppTDI",
proceso: "Para usar o aplicativo corretamente e que nos forneça as alternativas de decisão que melhores se apresentam. Primeiramente, devemos ter clareza sobre qual é o ativo que vamos negociar e, desta forma, inserir os dados que identificam o ativo (p.e Nasdaq, SP500, EURUSD, etc). Na opção designada para essa variável. Ademais, é muito importante definir qual é o prazo em que vamos analisar, para configurar de forma correta o aplicativo AppTDI©. Se este é: mensal, semanal, diário, 4 horas, 1 hora, 15min ou 5min, como os mais usados. Tendo em conta que, ao inserir os dados da terceira variável, CONTEXTO. Refere-se ao comportamento do preço com relação ao período imeadiatamente anterior, p.e. se o nosso período principal é de 1 hora, o período do contexto deveria estar 15min abaixo e 4 horas acima para ter uma melhor visualização desse contexto. Com a finalidade de evitar erros por parte do usuário/aluno e/ou trader/investidor quando vai executar do AppTDI, ele já vem configurado em algumas das opções, a mais lógica, de acordo com a variável anterior previamente determinada na variável LOCALIZAÇÃO. Portanto, isso vai nos permitir a situarmos no tempo e a inserir a informação correta para que o AppTDI©, nos forneça a melhor alternativa de decisão que devemos tomar nesse momento. Ademais, é muito importante estar atualizando as informações do comportamento do preço que vamos observando, segundo o período de tempo definido para a análise, dado que, como sabemos, o mercado é dinâmico e está em constante movimento. Logo, devemos atualizar permanentemente a informação do AppTDI©, de acordo com a variável Período de Tempo, da nossa análise. E cumprir com o propósito da ferramenta que é ter disciplina no monitoramento do mercado. Derechos Reservados Copyright. AppTDI©.O instrumento que sugerimos que deve-se utilizar é um dos mais populares e usados pelos especialistas e investidores do setor. A Vela Japonesa, dado que é o indicador que melhor reflete o comportamento do preço de um ativo financeiro em um período de tempo determinado e porque mostra o preço de abertura e de fechamento, o máximo e o mínimo, nível ao qual chegou a ser negociado durante um período de tempo, que é quando finalmente forma-se a vela.",
imagenes1: "q",
titulotendencia:"VARIÁVEL: TENDÊNCIA.",
tendencia: "A primeira variável ou etapa que devemos inserir no aplicativo, uma vez que tenhamos decidido anteriormente sobre o ativo a ser analisado ou negociado e o período de tempo no qual pretendemos operá-lo. É a Tendência. A qual pode ser Alta, Baixa ou Lateral. Qualquer ativo pode fazer somente esse movimento. Portanto, para inserir as informações nesta primeira variável, deve-se ir de acordo com o período de tempo principal, ou seja, (Marco de tempo selecionado para analisar e/ou negociar um ativo desejado, p.e: Daily, 4Hr, 1Hr, 15min 5min) sobre o qual vamos tomar certa decisão de investimento e estaremos dispostos a esperar no mínimo o mesmo tempo para obter um resultado. Nossa capacidade de identificar a tendência e operar na direção da tendência ofecerá a maior probabilidade em nossas operações e nos permitirá inserir os dados corretos exigidos pela variável um para configurar a melhor alternativa. Vamos nos concentrar nas 3 tendências primárias: a Tendência Alta, Tendência Lateral e Tendência Baixa. Para tendências altas e baixas, negociaremos na direção da tendência. Para a tendência lateral, você não deverá apenas identificá-la e entrar nesse tal elemento, o aplicativo AppTDI© se encarregará de mostrar se deve operar em algum sentido ou esperar para que se defina se tal tendência seja alta ou baixa. Procuraremos padrões, formações, eventos ou movimentos de correção no contrário da tendência para entradas a favor da tendência. As tendências frequentemente terminam quando revela-se uma lacuna de preços, quando tornam-se estendidas ou quando alcançam o Mínimo/Máximo em um período de tempo maior. Estamos atentos a esses movimentos chaves de reversão para evitar entrar muito tarde na tendência e, possivelmente, entrar na nova tendência mais cedo. Dessa forma, nosso aplicativo AppTDI© mostrará, uma vez que sejam inseridas as variáveis, qual é a melhor alternativa de decisão e o grau de prioridade. Você apenas deve atuar com determinação! Usaremos os saltos e/ou retrocessos ou formações de velas como mostrado no gráfico, para determinar a tendência H = High ou Máximo, L = Low ou Mínimo.",
imagenes2: "q",
tituloalcista:"Tendência Alta:",
alcista: "É estabelecido com 2 Retrocessos nas Pontas Superiores (RPM) e 2 Saltos nas Pontas Inferiores (RIP). Conhecidos tecnicamente como Pivots.",
imagenes3: "q",
titulobajista:"Tendência Baixa:",
bajista: "É estabelecido com 2 retrocessos nas Pontas Superiores (RPS) e 2 saltos nas Pontas Inferiore  (RPI). O Pivots Points.",
imagenes4: "q",
titulolateral:"Tendência Lateral:",
lateral: "As tendências laterais podem continuar com a tendência prévia ou iniciar uma nova tendência em direção oposta. Negociar dentro de uma tendência lateral pode apresentar oportunidades em ambas as direções. Pode ser gerado de suas formas, se vier de uma tendência alta ou baixa, respectivamente. Quando é precedida por uma tendência alta: Uma tendência lateral pode ser uma correção no meio de uma tendência alta, pode-se definir com 2 Retrocessos em Ponta ou mais em Zonas de Preços Superiores (ZPS) relativamente iguais e 2 Saltos em Ponta ou mais em Zonas de Preços Inferiores (ZPI) relativamente iguais e tendencioso à tendência anterior (alta).",
imagenes5: "q",
lateralb:"Quando é precedida por uma tendência baixa: Uma tendência lateral pode ser uma correção dentro de uma tendência baixa e pode ser definida com 2 ou mais Saltos em Ponta em Zonas de Preços Inferiores (ZPI) relativamente iguais e 2 ou mais Retrocessos em Ponta em Zonas de Preços Superiores (ZPS) relativamente iguais e tendencioso à tendência anteriores (baixa).",
imagenes6: "q",
lateralc: "Abreviação requerida para inserir a variável de tendência na página do AppTDI. • Alta, • Baixa, • Lateral",
titulolocaliza:"VARIÁVEL: LOCALIZAÇÃO:",
lacaliza: "Esta variável refere-se à localização que o preço do ativo financeiro está tendo, no período de tempo principal ou escolhido para negociar e o qual pretendemos atualizar para negociá-lo e tomar uma decisão de investimento. Como na variável Tendência, é muito importante definir corretamente a opção para esta variável, e definir onde está localizado o preço para obter a melhor opção. E, para isso,vamos dar uma explicação sobre o significado de cada uma das opções que temos para esta variável. Nos mercados financeiros existe uma variedade de instrumentos e ferramentas (indicadores e osciladores) para serem usados na análise técnica dos mercados de valores, tais como: barras de preço, linhas, Macd, RSI, Ichimoku, Níveis Fibonacci, Médias Móveis, Exponenciais ou linhas de tendência, etc. E ser considerado para fazer a conhecida análise técnica. Como nós falamos, vamos concentrar na ação do preço; representado pela vela japonesa. E sua Localização em zonas de preço conhecidas também como zonas de suporte e/ou resistência, que podem servir para determinar a localização do preço dentro da tendência. Devemos nos lembrar que o único suporte e resistência Verdadeiro e Real é o “Preço” e essa é a chave da Análise Técnica Objetiva. Os verdadeiros e reais Suporte e Resistência são os Máximos e Mínimos de Preços de velas prévios, uma série de Velas de Preços que formam uma base ou um vazio de preços não preenchido entre as velas de preço. No gráfico, é possível observar a Localização do preço em níveis onde, normalmente, os preços saltam ou retrocedem, formando e confirmando as tendências. É aqui onde devemos observar e analisar muito bem qual é a localização do preço para inserir corretamente a opção LOCALIZAÇÃO requerida na página do AppTDI.",
imagenes7: "q",
lacalizab: "Para inserir essa variável ao nosso AppTDI©, vamos definir cada uma das opções que estarão disponíveis em uma lista de seleção e será de fácil manejo para o usuário do aplicativo. Tecnicamente, o preço de um ativo financeiro sempre estará localizado em uma zona de preços em relação com a tendência prévia ou simplesmente se encontrará em um vazio de preços. Mas, basicamente, o preço estará localizado nessas zonas. É de importância vital analisar o comportamento do preço do ativo a ser negociado para inserir a informação correta e que nosso aplicativo possa mostrar a melhor opção para esse momento do mercado.",
titulolocalizac:"Localização das opções de Escolha Variável:",
lacalizac: "Retrocessos em Zonas de Preços Potentes Superiores: ou também chamadas de Resistência Maior, esta opção deve ser escolhida somente quando o preço se encontra na tendência lateral e o preço tiver feito Retrocessos em uma Zona de Preços Potente na parte superior, ao menos duas vezes como mostrado no gráfico. Uma Tendência Lateral pode ser uma correção dentro de uma tendência baixa.Tendendo a favor da tendência anterior (baixa).",
imagenes8: "q",
lacalizad: "Retrocessos em Zona de Preços Superior: ou também conhecida como Resistência Menor, esta opção deve ser escolhida quando o preço se encontra na tendência baixa e o preço tiver rompido uma Zona de Preços mínimos prévios, ou linha de suporte prévio, e Retrocede até o nível de preços que se rompeu. Tecnicamente, esse movimento é conhecido como ruptura de suporte, que agora se converte em resistência. É essa zona de preços onde deve-se buscar a melhor entrada para se posicionar em intervalos ou vendas, tendo em conta que a vela do período de tempo escolhido é formada.",
imagenes9: "q",
lacalizae: "Saltos em Zonas de Preços Potentes Inferiores: ou também conhecida como Suporte Maior, esta opção deve ser ecolhida somente quando o preço se encontra em tendência lateral e o preço tenha feito Saltos em uma Zona de Preços Potente na parte inferior, ao menos duas vezes como é mostrado no gráfico. Uma Tendência Lateral pode ser uma correção dentro de uma tendência alta. Tendendo a favor da tendência prévia (alta).",
imagenes10: "q",
lacalizaf: "Salto para a Zona de Preços Inferior: ou também conhecida como Suporte Menor, esta opção deve ser escolhida quando o preço se encontra em tendência alta e o preço tenha rompido uma linha de resistência prévia, máximos prévios e salta nos níveis de preço que se rompeu. E nessa zona de preços onde deve-se buscar a melhorar entrada para se posicionar em longos ou compras, tendo em conta que a vela do período de tempo escolhido está formada.",
imagenes11: "q",
vacio: "Vazio: Esta opção deve ser escolhida quando, basicamente, o preço não tenha níveis ou zonas de preço próximos, mínimos ou máximos de velas prévias, ou uma série de velas, o que pode indicar um nível de Resistência ou Suporte. Porém, os mesmos fatores são tomados como os seguintes níveis de Suporte ou Resistência. Na tendência lateral, os possíveis saltos ou retrocessos com falhas são favorecidos.",
titulocontexto:"VARIÁVEL: CONTEXTO:",
contexto: "Nesta variável, devemos inserir em nosso AppTDI© o Contexto e faz referência ao comportamento do preço analisando os períodos de tempo. Portanto, como mencionamos, é necessário definir previamente, na opção PERÍODO DE TEMPO. Qual será esse período d tempo para observar o comportamento do ativo financeiro que decidimos negociar ou analisar em determinado momento. Quando todos os períodos de tempo estiverem alinhados, as probabilidades aumentam. Cada período de tempo pode ter uma tendência distinta e esperar que todos os períodos de tempo estejam alinhados pode provocar indecisão. Portanto, no uso do AppTDI©, você deve observar qual é o comportamento que está tendo o preço do ativo no período de tempo inferior com relação ao seu período de tempo principal, ou seja, período de tempo escolhido para negociar, ou analisar, frente a seus períodos de tempo inferiores, para poder perceber seu contexto e inserir a opção correta.",
contextoa: "A seguir, sugerimos os períodos de tempo mais adequados para analisar e inserir no aplicativo. O período Mensal com o Período Semanal para uma Estratégia Core. O período Semanal com o período Diário para uma Estratégia Swing. O período Diário com o período de 4 horas para uma Estratégia Swing – Intradiária. O período de 4 horas com o período de 1 hora para uma Estratégia – Intradiária. O período de 1 hora com o período de 15 minutos para uma Estratégia Intradiária – Scalp. O período de 15 minutos com o período de 5 minutos para uma Estratégia Scalping. É sua decisão escolher qual é a estratégia sobre o PERÍODO de TEMPO a sua escolha e que se adeque às suas expectativas ou metas de investimento que mais condiz com o seu estilo de trading, grau de aversão ao ricos e sua natureza. Recomendamos que tenha isso em conta e revise nosso Disclaimer. É muito importante atualizar a informalção do AppTDI© cada vez que o período de tempo principal for cumprido e se forme a vela do PERÍODO DE TEMPO PRINCIPAL escolhido e selecionado para a análise ou gestão de seu investimento. Lembre-se, uma vela não é formada até que se forme, não antecipe, nunca se sabe o que pode acontecer nos mercados!",
titulocontextob:"Opções Variável Contexto:",
contextob: "Impulsivo à Tendência: Esta opção faz referência ao movimento que o preço está tendo desde o período de tempo inferior sobre o principal, o qual foi escolhido para ser analisado e/ou negociado. (p.e. Se decido escolher o Período de Tempo de 4 horas, devo observar como estão se comportando os períodos de tempo inferiores com relação ao de 4 horas e, como mencionado, tende a impulsionar a tendência).",
contextoc: "Corretivo de Tendência: Esta opção faz referência ao movimento que está tendo o preço do ativo financeiro selecionado, desde seu período de tempo inferior sobre o período de tempo principal ou selecionado para ser analisado e/ou negociado. E faz referência ao que está tendendo a se corrigir com relação à tendência que foi selecionada na Variável Tendência. (p.e. Se a variável Baixa de tendência for escolhida, o comportamento esperado é de que o preço se corrija). Extremidade da Faixa: Esta opção faz referência à localização do preço do ativo financeiro selecionado para observação ou negociação do período de tempo inferior sobre o período de tempo principal selecionado para ser analisado e/ou negociado.",
nota: "*Nota: com o propósito de minimizar a margem de erro por parte do estudante, quando se faz uma escolha correta das duas primeiras variáveis, as possíveis escolhas para essa variável poderão ser reduzidas a, inclusive, somente uma. Ou seja, você só precisa escolher. Dado que em certos momentos do mercado o preço nestas zonas de preços não tem muitas opções para se mover, devido às zonas onde se encontra.",
tituloglosario:"GLOSSÁRIO E TERMINOLOGIA:",
glosario: "Mercados de ações: É o lugar onde as forças da oferta e da demanda de ativos financeiro e de capital se encontram. Podem ser físicos, eletrônicos, etc. (NYSE, CME, CBO, NASDAQ, BOVESPA, NYKKEI, FTSE, etc.) Ativo financiero: É um instrumento que contém um valor econômico e o qual representa a tendência ou a representação de propriedae sobre uma parte de um bem, pode ser de uma ação de uma empresa ou outro título de valor, por exemplo, ações da Apple, Amazon, Google, etc. Ou índices como o Dow Jones, S&P500 ou Nasdaq, em Forex EURUSD, GBPUSD, USDCHF, etc. Ou de qualquer outro instrumento financeiro existente. Vela Japonesa: É um indicador financeiro que é usado há séculos para definir o preço do ativo ou bem, tendo um preço de Abertura, Fechamento, um Máximo ao que foi negociado e um Mínimo ao que foi negociado, em um determinado período de tempo. Período de Tiempo: Refere-se ao tempo definido de análise de um determinado ativo financeiro. Por exemplo, Mensal, Semanal, Diário, 4 horas, 1 hora, 15 minutos e 5 minutos. Opcções Binárias: instrumento financeiro de investimento o qual consiste em investir sobre um ativo financeiro que te oferece duas opções de investimento (Call – Put) e a opção de torná-lo eficaz em um determinado período de tempo. Firma Broker: Entidade financeira regulada para oferecer serviços de intermediação financeira e que oferece os outros serviços de acesso ao mercado através de uma conta ou carteira de investimento. Esses e muitos outros são alguns dos termos que você verá no manual e no aplicativo. Se você deseja alguma explicação especial sobre um termo ou vocabulário que não entenda, você pode me escrever e poderei, com prazer, te explicar e enriquecer este manual.",
tituloconclusion:"Conclusão:",
conclusion: "O sentido de criar este aplicativo foi o de aproximar o mercado das pessoas e ser uma ferramenta de apoio no gerenciamento de uma carteira de investimento, e que o usuário ou investidor tenha elementos de julgamento para tentar minimizar a margem de erro e evitar perdas de capital o máximo possível. Foi isso que me motivou a criar este Aplicativo e meu maior desejo é contribuir para que possa ter uma fonte adicional de renda.",
titulofinal:"Recomendação Final:",
final: "Como mencionei acima, não pretendo com este Aplicativo te prometer nada, só quero te ajudar e compartilhar o pouco que eu aprendi e vivi no mundo do Trading da Bolsa e a converter meu conhecimento e minha experiência em um instrumento que possa te ajudar. Este aplicativo é somente o ínicio, o primeiro passo, para que você inicie um caminho emocionante no trading, mas deve estar disposto a dar e a se preparar para ser cada vez melhor e possa gerar fontes de renda. Isso é o que mais desejo para sua vida.",
autor1: "Obrigado pela oportunidade,",
autor2: "Com Cariño",
autor2A: "John Alexander Vieira Marín",
autor3:"Criador AppTDI",
autor4: "www.apptdi.com",
linkapp:"https://apptdi.com/disclaimer/"
}]
}];

}
}
